# Generated by Django 3.0.8 on 2020-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Enter a delivery status (e.g. On transit)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Enter a parcel size (e.g. 20cm x 30cm x 50cm)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel_weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(help_text='Enter a parcel weight (e.g. 1kg)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ManyToManyField(help_text='Select a parcel size', to='order.Parcel_size')),
                ('status', models.ManyToManyField(help_text='Select a delivery status', to='order.Delivery_status')),
                ('weight', models.ManyToManyField(help_text='Select a parcel weight', to='order.Parcel_weight')),
            ],
        ),
    ]
