# Generated by Django 3.0.8 on 2020-11-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(help_text='Enter a vehicle type (e.g. bike)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_year', models.IntegerField(default=2000)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(help_text='Enter a brand(e.g. Renault)', max_length=30)),
                ('v_model', models.CharField(help_text='Enter a brand(e.g. Kangoo)', max_length=50)),
                ('plate', models.CharField(help_text='LLE3421', max_length=20)),
                ('comment', models.TextField(help_text='Enter a comment about behicle', max_length=1000)),
                ('v_type', models.ManyToManyField(help_text='Select a vehicle type', to='order.Vehicle_type')),
            ],
        ),
    ]
